steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/gcp-kubernetes-461810/demo-employee-image','demo-employee/.']

  # Push Docker image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/gcp-kubernetes-461810/demo-employee-image']

#images:
#  - 'asia.gcr.io/gcp-kubernetes-461810/demo-employee-image'

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
     #gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
     gcloud deploy apply --file deploy/dev.yaml --region=us-central1
     gcloud deploy apply --file deploy/prod.yaml --region=us-central1

     gcloud deploy releases create 'demo-employee-release-${SHORT_SHA) --delivery-pipeline=gke-cicd-1 --region=us-central1 --from-k8s-manifest=./kubernetes/demo-employee.yaml
options: 
   logging: CLOUD_LOGGING_ONLY
