steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','asia.gcr.io/gcp-kubernetes-461810/demo-employee-image','.']

  # Push Docker image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia.gcr.io/gcp-kubernetes-461810/demo-employee-image']