apiversion: deploy.cloud.google.com/vi
kind: DeliveryPipeline
metadata:
	name: gke-cicd-1
	labels:
		app: cicd

description: cicd delivery pipeline
serialPipeline:
	stages:
	- targetId: dev
	#profiles:
		# -dev

	#targetId: staging
	# profiles:
	# - staging

    - targetId: prod
	#profiles:
	# prod
